from __future__ import annotations

import threading
from typing import Any

from .chrome_tabs import AccessibleNode

PAGE_WINDOW_CLASS_PART = "RenderWidgetHost"

_this_thread = threading.local()


def open_chrome_window(hwnd: int) -> AccessibleNode:
    automation = getattr(_this_thread, "automation", None)
    if automation is None:
        automation = _this_thread.automation = _Automation()
    return automation.window(hwnd)


class _Automation:
    def __init__(self) -> None:
        import comtypes  # noqa: PLC0415  (COM starts on whichever thread imports it)
        import comtypes.client  # noqa: PLC0415

        comtypes.CoInitialize()
        comtypes.client.GetModule("UIAutomationCore.dll")
        from comtypes.gen import UIAutomationClient  # noqa: PLC0415  (generated by the line above)

        self.uia: Any = UIAutomationClient
        self.client: Any = comtypes.client.CreateObject(
            UIAutomationClient.CUIAutomation, interface=UIAutomationClient.IUIAutomation)
        self.read_with_each_node: Any = self.client.CreateCacheRequest()
        self.read_with_each_node.AddProperty(UIAutomationClient.UIA_ControlTypePropertyId)
        self.read_with_each_node.AddProperty(UIAutomationClient.UIA_ClassNamePropertyId)
        # Not FindAll, which switched on Chrome 154's accessibility for every open page.
        self.walker: Any = self.client.RawViewWalker

    def window(self, hwnd: int) -> _Node:
        return _Node(self, self.client.ElementFromHandleBuildCache(hwnd, self.read_with_each_node))


class _Node:
    def __init__(self, automation: _Automation, element: Any) -> None:
        uia = automation.uia
        control_type = element.CachedControlType
        self.is_tab = control_type == uia.UIA_TabItemControlTypeId
        self.is_page = (control_type == uia.UIA_DocumentControlTypeId
                        or PAGE_WINDOW_CLASS_PART in (element.CachedClassName or ""))
        self.is_active = self.is_tab and element.GetCurrentPropertyValue(
            uia.UIA_SelectionItemIsSelectedPropertyId) is True
        self._automation = automation
        self._element = element

    def children(self) -> list[_Node]:
        automation = self._automation
        found = []
        child = automation.walker.GetFirstChildElementBuildCache(self._element, automation.read_with_each_node)
        while child:
            found.append(_Node(automation, child))
            child = automation.walker.GetNextSiblingElementBuildCache(child, automation.read_with_each_node)
        return found

    def switch_to(self) -> None:
        uia = self._automation.uia
        self._element.GetCurrentPattern(uia.UIA_LegacyIAccessiblePatternId).QueryInterface(
            uia.IUIAutomationLegacyIAccessiblePattern).DoDefaultAction()
