from __future__ import annotations


BROKER_PANEL = "broker_panel"
FMODE_PANEL = "fmode_panel"
PORTRAIT_PREV = "portrait_prev"
PORTRAIT_NEXT = "portrait_next"
PORTRAIT_LOCK = "portrait_lock"
PORTRAIT_TRASH = "portrait_trash"
PRIMARY_PREV = "primary_prev"
PRIMARY_NEXT = "primary_next"
QUARTER_BUTTON = "quarter_button"
LANDSCAPE_PREV = "landscape_prev"
LANDSCAPE_NEXT = "landscape_next"
LANDSCAPE_LOCK = "landscape_lock"
LANDSCAPE_TRASH = "landscape_trash"
OPEN_FILE_DIALOG = "open_file_dialog"
CLIPPER_SAVE = "clipper_save"
VLC_NUDGE_PREV = "vlc_nudge_prev"
VLC_NUDGE_NEXT = "vlc_nudge_next"
GENAU_ACTIVATE = "genau_activate"
VLC_ACTIVATE = "vlc_activate"
HYBRID_ACTIVATE = "hybrid_activate"
GENAU_AMP_UP = "genau_amplitude_up"
GENAU_AMP_DOWN = "genau_amplitude_down"
GENAU_CTR_UP = "genau_center_up"
GENAU_CTR_DOWN = "genau_center_down"
GENAU_SPD_UP = "genau_speed_up"
GENAU_SPD_DOWN = "genau_speed_down"
GENAU_CRUISE = "genau_toggle_cruise"
GENAU_TOGGLE_AUTO = "genau_toggle_auto"
GENAU_SHAPE = "genau_cycle_shape"
QUIT_BUTTON = "quit"
OMNIPAUSE_TOGGLE = "omnipause_toggle"
VOICE_TOGGLE = "voice_toggle"
HELP_REFERENCE = "help_reference"
