from __future__ import annotations


BROKER_PANEL = "broker_panel"
FMODE_PANEL = "fmode_panel"
PORTRAIT_PREV = "portrait_prev"
PORTRAIT_NEXT = "portrait_next"
PORTRAIT_LOCK = "portrait_lock"
PORTRAIT_TRASH = "portrait_trash"
PRIMARY_PREV = "primary_prev"
PRIMARY_NEXT = "primary_next"
QUARTER_BUTTON = "quarter_button"
LANDSCAPE_PREV = "landscape_prev"
LANDSCAPE_NEXT = "landscape_next"
LANDSCAPE_LOCK = "landscape_lock"
LANDSCAPE_TRASH = "landscape_trash"
OPEN_FILE_DIALOG = "open_file_dialog"
CLIPPER_SAVE = "clipper_save"
VLC_NUDGE_PREV = "vlc_nudge_prev"
VLC_NUDGE_NEXT = "vlc_nudge_next"
GENAU_TOGGLE = "genau_toggle"
QUIT_BUTTON = "quit"
OMNIPAUSE_TOGGLE = "omnipause_toggle"
