from __future__ import annotations


BROKER_PANEL = "broker_panel"
FMODE_PANEL = "fmode_panel"
PORTRAIT_PREV = "portrait_prev"
PORTRAIT_NEXT = "portrait_next"
PORTRAIT_LOCK = "portrait_lock"
PORTRAIT_TRASH = "portrait_trash"
PRIMARY_PREV = "primary_prev"
PRIMARY_NEXT = "primary_next"
QUARTER_BUTTON = "quarter_button"
LANDSCAPE_PREV = "landscape_prev"
LANDSCAPE_NEXT = "landscape_next"
LANDSCAPE_LOCK = "landscape_lock"
LANDSCAPE_TRASH = "landscape_trash"
OPEN_FILE_DIALOG = "open_file_dialog"
CLIPPER_SAVE = "clipper_save"
PRIMARY_NUDGE_PREV = "primary_nudge_prev"
PRIMARY_NUDGE_NEXT = "primary_nudge_next"
NAU_RECORD = "nau_record_tap"
GENAU_ACTIVATE = "genau_activate"
NAU_ACTIVATE = "nau_activate"
HYBRID_ACTIVATE = "hybrid_activate"
GENAU_AMP_UP = "genau_amplitude_up"
GENAU_AMP_DOWN = "genau_amplitude_down"
GENAU_CTR_UP = "genau_center_up"
GENAU_CTR_DOWN = "genau_center_down"
GENAU_SPD_UP = "genau_speed_up"
GENAU_SPD_DOWN = "genau_speed_down"
GENAU_CRUISE = "genau_toggle_cruise"
GENAU_TOGGLE_AUTO = "genau_toggle_auto"
GENAU_SHAPE = "genau_cycle_shape"
QUIT_BUTTON = "quit"
OMNIMINIMIZE = "omniminimize"
OMNIRESTORE = "omnirestore"
OMNIPAUSE_TOGGLE = "omnipause_toggle"
VOICE_TOGGLE = "voice_toggle"
HELP_REFERENCE = "help_reference"
HELP_REFERENCE_CLOSE = "help_reference_close"
# The pair that drives only the dashboard's own reference popup: they open and
# dismiss a help window and reach no player, no shared state.  That is why the
# dispatch loop echoes them as a press and stops, and why omnipause — which
# freezes what a spoken command may do to the room — lets them through.
HELP_REFERENCE_COMMANDS = frozenset({HELP_REFERENCE, HELP_REFERENCE_CLOSE})
